#!/usr/bin/env python2
import eventdistr
from datetime import datetime

def opener(version, cmd, data):
	if data:
		print "%s: %s=%s (v%d)" % (datetime.now(), cmd, repr(data), version)
	else:
		print "%s: %s (v%d)" % (datetime.now(), cmd, version)


if __name__ == "__main__":
	eventdistr.run_listener(opener)