#!/usr/bin/env python2
import eventdistr

def opener(version, cmd, data):
	if data:
		print "%s: %s (v%d)" % (cmd, repr(data), version)
	else:
		print "%s (v%d)" % (cmd, version)


if __name__ == "__main__":
	eventdistr.run_listener(opener)