#!/usr/bin/env python2
import eventdistr
import time
import urllib
import json

SPACE_API_URL = "http://status.stratum0.org/status.json"

""" Returns boolean whether space is open, or None of error """
def fetchStatus():
	s = None
	o = None
	try:
		u = urllib.urlopen(SPACE_API_URL)
		s = u.read()
	except IOError as e:
		print "Oops. Could not retrieve status: %s" % e
		return None
	try:
		o = json.loads(s)
	except ValueError as e:
		print "Oops. Could not parse status: %s" % e
		print "JSON string was: %s" % s
		return None
	# strict type-checking
	if o["open"] == True:
		return True;
	if o["open"] == False:
		return False;
	else:
		return None;

lastopen = 0
def opener(version, cmd, data):
	global lastopen
	if cmd == eventdistr.EVENT_DING_DONG:
		now = time.time()
		if now - lastopen > 15:
			if fetchStatus():
				print "Somebody is ringing the door, let me fix that for you"
				eventdistr.open_door()
				lastopen = now
			else:
				print "Somebody is ringing the door, but we're closed."
		else:
			print "Flood control."


if __name__ == "__main__":
	eventdistr.run_listener(opener)
# vim: set noet sw=2 ts=2 ai si:
