#!/usr/bin/env python2
import eventdistr
import time
import urllib2
import json
import datetime

SPACE_API_URL = "http://status.stratum0.org/status.json"

def is_open():
	aResp = urllib2.urlopen(SPACE_API_URL)
	data = aResp.read();
	data = json.loads(data)
	if "isOpen" in data:
		return data["isOpen"]
	return False


lastopen = 0

def opener(version, cmd, data):
	global lastopen
	if cmd == eventdistr.EVENT_DING_DONG:
		now = time.time()
		if now - lastopen > 15:
			print datetime.datetime.now()
			if is_open():
				print "Somebody is ringing the door, let me fix that for you"
				eventdistr.open_door()
			else:
				print "Sorry we are closed right now"
			lastopen = now


if __name__ == "__main__":
	eventdistr.run_listener(opener)